
name: build_osx

on:
  # Enable manual run from the Actions tab
  workflow_dispatch:

jobs:
  run-testsuite:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-11', 'macos-12', 'macos-13', 'macos-14']
    runs-on: '${{ matrix.os }}'
    name: 'Run Testsuite'
    steps:
      - uses: actions/checkout@v4
      - name: 'Run testsuite'
        run: development/testsuite

  install-macports:
    strategy:
      matrix:
        os: ['macos-11', 'macos-12', 'macos-13', 'macos-14']
        version: ['2.9.3']
        prefix: ['/opt/local']
    runs-on: '${{ matrix.os }}'
    name: 'Install MacPorts'
    needs: 'run-testsuite'
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: 'macports'
        with:
          parameters: 'testsuite/run-testsuite-on-${{ matrix.os }}.yaml'
      - name: 'Validate installed MacPorts version'
        run: >-
          test "$(port version)" = 'Version: ${{ matrix.version }}'
      - name: 'Validate transmitted MacPorts prefix'
        run: >-
          test "${{ steps.macports.outputs.prefix }}" = '${{ matrix.prefix }}'
      - name: 'Validate transmitted MacPorts version'
        run: >-
          test "${{ steps.macports.outputs.version }}" = '${{ matrix.version }}'
      - run: port version
  build:
    runs-on: macos-12

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Build-commands
        run: |
          sudo port install ccache
          echo Starting Build-commands
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          uname -a
          cd $GITHUB_WORKSPACE
          ls -lh
          cd src
          make
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: reseek-osx-binary
          path: $GITHUB_WORKSPACE/reseek/bin/reseek
