name: build-osx-x86

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-13
 
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Install MacPorts (new step)
      - uses: melusina-org/setup-macports@v1

      - name: Install dependencies
        run: |
          sudo port install python311
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  
          brew update
          brew install gcc@11

      # Runs a set of commands using the runner's shell
      - name: Build-commands
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x ./build_osx_x86.bash
          ./build_osx_x86.bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: reseek-osx-x86
          path: /Users/runner/work/reseek/reseek/bin/reseek
