name: build_linux

on:
  workflow_dispatch:

permissions:
  contents: read    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    

jobs:
  build:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
           python-version: '3.10' 

      # Runs a set of commands using the runners shell
      - name: Build-commands
        run: |
          sudo apt-get install -q -y ccache
          echo Starting Build-commands
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          cd src
          chmod u+x ./build_linux.bash
          ./build_linux.bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: reseek-linux-binary
          path: /home/runner/work/reseek/reseek/bin/reseek
