name: build-osx-x86

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up MacPorts
        uses: melusina-org/setup-macports@v1
      - name: Update MacPorts and sync ports
        run: |
          sudo port selfupdate
          sudo port sync
      - name: Install Python 3.11
        run: sudo port install python311
          brew update
          brew install gcc@11

      # Runs a set of commands using the runner's shell
      - name: Build-commands
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x ./build_osx_x86.bash
          ./build_osx_x86.bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: reseek-osx-x86
          path: /Users/runner/work/reseek/reseek/bin/reseek
