
name: build_osx

on:
  # Enable manual run from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Build-commands
        run: |
          sudo port install ccache
          echo Starting Build-commands
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          uname -a
          cd $GITHUB_WORKSPACE
          ls -lh
          cd src
          make
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: reseek-osx-binary
          path: $GITHUB_WORKSPACE/reseek/bin/reseek
