name: build_linux

on:
  workflow_dispatch:

permissions:
  contents: read    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    

jobs:
  build:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Build-commands
        run: |
          sudo apt-get install -q -y ccache
          echo Starting Build-commands
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          uname -a
          cd $GITHUB_WORKSPACE
          ls -lh
          cd src
          make
          file /home/runner/work/reseek/reseek/bin/reseek | grep x86-64
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: reseek-linux-binary
          path: /home/runner/work/reseek/reseek/bin/reseek

  build-aarch64:
    name: Linux aarch64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu20.04
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          --volume "${PWD}:/reseek"
        install: |
          apt-get update -q -y
          apt-get install -q -y make g++ file git ccache
        run: |
          git config --global --add safe.directory /
          cd /reseek  
          uname -a
          lscpu
          cd src/
          make 
          file /reseek/bin/reseek | grep aarch64

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: reseek-linux-aarch64-binary
        path: /reseek/bin/reseek
    
